#!/usr/bin/env bash
#: Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line using while loop and if statement
n=1
while [ $n -le 10 ]
do
        if [[ $n -eq 9 ]]
        then
                echo "Best School"
                echo "Hi"
        else
                echo "Best School"
fi
        ((n++))
done
